Added better diagnostics to publishing

diff --git a/.github/workflows/publish-protobuf.yaml b/.github/workflows/publish-protobuf.yaml
--- a/.github/workflows/publish-protobuf.yaml
+++ b/.github/workflows/publish-protobuf.yaml
@@ -39,7 +39,13 @@ jobs:
           do 
             if ! curl --silent --head --output /dev/null --fail \
                 "${LOKI4J_MVN_PATH}/loki-protobuf/${VER}_pb${PBVER}.0/loki-protobuf-${VER}_pb${PBVER}.0.jar"; then
-              echo "${PBVER} is not published"
+              echo "${PBVER} is not published. Running publish command..."
+              gradle \
+                  -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} \
+                  -Psigning.secretKeyRingFile="$(pwd)/.gradle/secring.gpg" \
+                  -PpubToOSSR -PpbVersion=${PBVER}.0 :loki-protobuf:publish \
+                || echo "Publishing of ${PBVER} failed"
+              echo "${PBVER} published successfully"
             fi
           done < loki-protobuf/PB-VERSION
       - name: Cleanup
